### ISSUE TITLE
UUDID Issue

### ISSUE THREAD

**Issue by minhajakhterkhan199** [ecc1/ble#2]
Please advise how to know the UUID of device. 
In addition, please also advise this is UUID of Host device or remote device. 
https://github.com/ecc1/ble/blob/master/cmd/pair/main.go

**Comment by minhajakhterkhan199** [comment]
Waiting for your response

**Comment by ecc1** [comment]
You need to discover the UUID of the device you're interested in.  You can use discover mode in the ```bluetoothctl``` command or other Bluetooth tools for this.
