### ISSUE TITLE
what is the api for disconnecting sensors?

### ISSUE THREAD

**Issue by saurabh-newera** [ecc1/ble#4]
can i use  conn.Close()  for disconnecting sensors?

**Comment by ecc1** [comment]
conn.Close will just close the local dbus connection; it won't affect connected devices.

I just added the device Disconnect method in https://github.com/ecc1/ble/commit/379c4f6898aa234ca0f4571f25e5ee31f9070e17

I don't have an easy way to test it, so please let me know whether it works.

**Comment by ecc1** [comment]
I was able to test it (added an example disconnect program), so I'm closing this.

**Comment by saurabh-newera** [comment]
api for disconnecting sensor is working. Thank you
